### ISSUE TITLE
can help，clearkey rsa how to use

### ISSUE THREAD

**Issue by bryanyeong97** [DevLARLEY/ClearKeyRSA#1]
admin can do a video teach，how to use clearkey rsa to get key，thanks

**Comment by DevLARLEY** [comment]
what website are you trying to get the keys from? DMM?

**Comment by bryanyeong97** [comment]
yes，can help，how to edit the clearkey scripts，i can share my account，can
help and teach me，thanks

**Comment by DevLARLEY** [comment]
Is it dmm.com or dmm.co.jp?

**Comment by bryanyeong97** [comment]
dmm.co.jp
i can share my account, admin got telegram or discord, my telegram: https://t.me/bryan_yeong97

**Comment by DevLARLEY** [comment]
```python
rsa = ClearKey_RSA()

response = requests.post(
    url='https://mlic.dmm.co.jp/drm/clearkey/license',
    cookies={
        'licenseUID': '',  # licenseUID cookie
    },
    data={
        'kids': [
            # key IDs from your request
        ],
        'type': 'temporary',
        'spki': rsa.export_spki()
    }
)

data = response.json()

for key_data in data['keys']:
    kid_hex = rsa.pad_b64_to_bytes(key_data['kid']).hex()
    decrypted_hex = rsa.decrypt_key(key_data['k']).hex()

    print(f"{kid_hex}:{decrypted_hex}")
```

**Comment by bryanyeong97** [comment]
> ```python
> rsa = ClearKey_RSA()
> 
> response = requests.post(
>     url='https://mlic.dmm.co.jp/drm/clearkey/license',
>     cookies={
>         'licenseUID': '',  # licenseUID cookie
>     },
>     data={
>         'kids': [
>             # key IDs from your request
>         ],
>         'type': 'temporary',
>         'spki': rsa.export_spki()
>     }
> )
> 
> data = response.json()
> 
> for key_data in data['keys']:
>     kid_hex = rsa.pad_b64_to_bytes(key_data['kid']).hex()
>     decrypted_hex = rsa.decrypt_key(key_data['k']).hex()
> 
>     print(f"{kid_hex}:{decrypted_hex}")
> ```

import requests
import base64
from Cryptodome.PublicKey import RSA
from Cryptodome.Cipher import PKCS1_OAEP
from Cryptodome.Hash import SHA256


class ClearKey_RSA:
    def __init__(
            self,
            key_length=2048
    ):
        """
        Decrypts RSA encrypted ClearKey responses
        Author: github.com/DevLARLEY
        """
        self.private_key = RSA.generate(key_length)
        self.public_key = self.private_key.publickey()

    def export_spki(self) -> str:
        spki = self.public_key.export_key(format='DER')
        return base64.b64encode(spki).decode('utf-8')

    @staticmethod
    def pad_b64_to_bytes(encoded_str):
        return base64.b64decode(encoded_str.replace('-', '+').replace('_', '/') + '==')

    def decrypt_key(self, b64_key: str) -> bytes:
        cipher = PKCS1_OAEP.new(self.private_key, hashAlgo=SHA256)
        return cipher.decrypt(self.pad_b64_to_bytes(b64_key))


if __name__ == '__main__':
    rsa = ClearKey_RSA()

    response = requests.post(
        url='https://mlic.dmm.co.jp/drm/clearkey/license',
        cookies={
            'licenseUID': 'be2a1eAa5ed3bA1D18A8dee0A9a991',  # licenseUID cookie
        },
        data={
            'kids': [
                "2UUiunASM5OGTVhtkmbgMQ",
                "AAAAAAAAAAAAAAAAAAAAAA",
                "eyJ2IjoiMiIsImZpZCI6Ig",
                "MXN0Y3YwMDQwOCIsInN2aQ",
                "ZCI6ImRpZ2l0YWwiLCJwbA",
                "IjoiZXlKd2FXUWlPaUl4Yw",
                "M1JqZGpBd05EQTRJaXdpWg",
                "R1ZzYVhabGNubGZkSGx3Wg",
                "U0k2SW5OMEluMCIsImNzIg",
                "OiIyOWQyYzUzY2NhZGFjMg",
                "MmNmNzZkMmQ2OWMxN2JkZg",
                "YmEifQAAAAAAAAAAAAAAAA"
            ],
            'type': 'temporary',
            'spki': rsa.export_spki()
        }
    )

    data = response.json()

    for key_data in data['keys']:
        kid_hex = rsa.pad_b64_to_bytes(key_data['kid']).hex()
        decrypted_hex = rsa.decrypt_key(key_data['k']).hex()

        print(f"{kid_hex}:{decrypted_hex}")

correct?

**Comment by bryanyeong97** [comment]
![Screenshot 2024-10-05 175404](https://github.com/user-attachments/assets/a087da2c-d744-422b-b928-0d92108985ff)

**Comment by bryanyeong97** [comment]
admin can try to do a tutorials video demo，thanks

**Comment by DevLARLEY** [comment]
post the `Copy as cURL (POSIX)`/`Copy as cURL (bash)` from the request

**Comment by bryanyeong97** [comment]
> post the `Copy as cURL (POSIX)`/`Copy as cURL (bash)` from the request

can help me see and edit, i dont where got wrong, run also error, thanks
[clearkey_rsa.py.txt](https://github.com/user-attachments/files/17265991/clearkey_rsa.py.txt)
![Screenshot 2024-10-05 192435](https://github.com/user-attachments/assets/c84843bf-6207-4796-bb09-287bffafbb2d)

**Comment by DevLARLEY** [comment]
just do what i said
post the Copy as cURL (POSIX)/Copy as cURL (bash) from the request

**Comment by bryanyeong97** [comment]
> just do what i said post the Copy as cURL (POSIX)/Copy as cURL (bash) from the request

I follow already, but also get wrong😂

**Comment by bryanyeong97** [comment]
import requests

cookies = {
    'rieSh3Ee_ga': 'GA1.1.928391635.1711867150',
    '_yjsu_yjad': '1711867150.e0d8b076-7218-4c71-a9c6-ee3021ac7de2',
    '_dga': 'GA1.3.1802963100.1711867142',
    '_ga': 'GA1.3.1802963100.1711867142',
    'i3_ab': '7f000851-439f-49f0-8619-f631fcb679be',
    '_tt_enable_cookie': '1',
    '_ttp': 'Yd1R05Iq1z2XEF4UdIMdBmviasZ',
    'digital[play_volume]': '0.5',
    'adpf_uid': 'UQWyxQwICRcVLVpb',
    'uid': 'dRXBoGDBeOBSEJqtTOdP',
    'suid': 'dRXBoGDBeOBSEJqtTOdP',
    'check_done_login': 'true',
    'dtms': '10',
    'd_mylibrary': 'nINks%2BxgI%2F1I329WV6UBoA%3D%3D',
    'universe_aid': '350ce30483a87c8e22f7a652a0055267',
    'd_certify': '2024-03-31+15%3A44%3A33',
    'digital[play_muted]': '1',
    'deviceIdentify': 'TqiLBvL2steK6atdgAwBkMWwe2mtjb',
    'top_dummy': '355138b2-e0d1-41a3-a572-abef455215e6',
    'digital[play_heatmap]': '1',
    'subscription_members_status': 'non',
    'guest_id': 'VxZRShRMC0pCVQcP',
    'dtmu': 'YToyOntzOjI6Iml2IjtzOjg6IiqckZos_j4ZIjtzOjU6InZhbHVlIjtzOjI0OiISSVwxDtQ2LTylnBLQCuERSiqfGXQpouEiO30',
    'dtmh': '3.b10b67e794d0ac573f6e792aacc6c130058bd055338a4951e6ffb265a331b90f',
    '_cq_duid': '1.1723207646.J6hWbU0LNYD2PoP4',
    '_clck': '68vg3q%7C2%7Cfoe%7C0%7C1690',
    'top_pv_uid': '8bfb0ca0-11a9-4cf9-bca2-2e2be689d79e',
    'cdp_id': 'VkCih9XdqvZITYB6',
    'digital[play_bitrate]': '%E9%AB%98%E7%94%BB%E8%B3%AA%20(576p)',
    'ixd_lastclick': '6828,1726885088',
    '_gcl_au': '1.1.776536611.1727485373',
    'age_check_done': '1',
    '_gid': 'GA1.3.788114191.1727873719',
    'has_althash': 'V1ECDEsGUB8IVhEJAwxXDltWBA__',
    'althash': '101000-1af2752a-f842-f11d-8df0-0731820d6065',
    'i3_opnd': 'VkCih9XdqvZITYB6',
    'ckcy_remedied_check': 'ktkrt_argt',
    'adult_link_disable': '1',
    '__utmc': '125690133',
    '__utmz': '125690133.1728091176.327.213.utmcsr=accounts.dmm.co.jp|utmccn=(referral)|utmcmd=referral|utmcct=/service/login/password/=/path=https%3A%2F%2Fwww.dmm.co.jp%2Fdigital%2F-%2Fmylibrary%2Fsearch%2F',
    '_cq_suid': '1.1728091177.HtNYGlvdshEO4J84',
    'licenseUID': 'be2a1eAa5ed3bA1D18A8dee0A9a991',
    'sort_search': 'eyJzZWFyY2hzdHIiOiIifQ%3D%3D',
    'list_condition': '%7B%22digital%22%3A%7B%22limit%22%3Anull%2C%22sort%22%3A%22date%22%2C%22view%22%3Anull%7D%7D',
    'LSS_SESID': 'A1lRXE9CCQJYQTR6d0cKEF9WAFkQOxNzQQRVCSQlcycjKCoQVwBfcCMiIHJQRwoQX1EOQWE1JWJtFl1YX1UFUFpTW14DBgIKEVlYCREpYjA6N3EweyVGC1gOVQseFwhbWEEOB0dFbEINERURCBYLV19GUAJGBEYLSg5RC0cAWwULFwMKFgpAC1ZZQ1dSEVRBXhcOVwhDEllcQ0QKFl4CWEBBWRtJ',
    'dig_history': 'ddh280%2Cntk033%2Cion209%2Csgk145%2Csmjz051%2Chmdnc738%2Cdocs004',
    'is_intarnal': 'false',
    'INT_SESID': 'A1lRXE9CCQJYQTR6d0cKEF9XAlkQB1EICQIDUwdJAgZUBk9SUABRHANXVAYeBwRbVlIEVFcHVARfFl1CX1EIQDE3IzRgEwhYWFJWAQtVCFJUUwVYQVtdCht9KGU6N3cxKydAXVULBAsZEFsACUdkKiFGDxAIUlIKGwBWAFdcBgNUTldRVQQeBVsHVh4KVghQSFENV1RSBgdYBAMDBEYJEVhaWERZVF5TBxE%2BWldHChBfVQZZECVVAAlBHwkHBgIRW0FZFQ4ECRMGAT5aV0cKEF9VDkEGQ19DAwNcExAXVxA9CgZED0IJAFRZQ2VYJlgLXDxQEkQ7LWRgdlATXhcIW1hBAxNAWWxFCw4EEQgMC1JSVgxSA1dQBQAPFQtUVQhABhYSCl1SUkULDA8RCBYLU19GFlhBW1UIAxYPQjoFVAQLDwsHQFRsXhUNBEERXlNZVV9JHg%3D%3D',
    'INT_SESID_SECURE': 'A1lRXE9CCQJYQTR6d0cKEF9XAlkQB1EICQIDUwdJAgZUBk9SUABRHANXVAYeBwRbVlIEVFcHVARfFl1CX1EIQDE3IzRgEwhYWFJWAQtVCFJUUwVYQVtdCht9KGU6N3cxKydAXVULBAsZEFsACUdkKiFGDxAIUlIKGwBWAFdcBgNUTldRVQQeBVsHVh4KVghQSFENV1RSBgdYBAMDBEYJEVhaWERZVF5TBxE%2BWldHChBfVQZZECVVAAlBHwkHBgIRW0FZFQ4ECRMGAT5aV0cKEF9VDkEGQ19DAwNcExAXVxA9CgZED0IJAFRZQ2VYJlgLXDxQEkQ7LWRgdlATXhcIW1hBAxNAWWxFCw4EEQgMC1JSVgxSA1dQBQAPFQtUVQhABhYSCl1SUkULDA8RCBYLU19GFlhBW1UIAxYPQjoFVAQLDwsHQFRsXhUNBEERXlNZVV9JHg%3D%3D',
    'secid': 'a3faf9e87c749459be32d42be968770f',
    'login_secure_id': 'a3faf9e87c749459be32d42be968770f',
    'login_session_id': '401284a6-57a5-49d7-9393-594f3b7a0e2a',
    'cto_bundle': '0TF75l8lMkJzdjFWYmU1QkUzUGRuNGpxJTJGa3ZaOFo1blBnZW9IdjNLcU1FdmtVemQ2dDZZdWN6cDFZS0cyeDc4YndQelElMkJKanVVYmlJVkVtMWdLMEVOSVRjUndIaDlJYURlcURMd0laYVQ4VDJmWmFRamNwdVdEbzFHZENtNGtEMk1iQnRISXlpV0l1REZXSWJ2ekRaNUtLQnlxaEw0aUVRMnd6cGpudGJrMGhFZGFUNndSRUEzbjIlMkJEUTZySnJBJTJGOFFjaE5Jb0tGQWYxeEQzdWhHY011NDRZWnNwUSUzRCUzRA',
    'rieSh3Ee_ga_KQYE0DE5JW': 'GS1.1.1728114602.67.1.1728116470.0.0.1712278297',
    '__utma': '125690133.1802963100.1711867142.1728121435.1728126804.332',
    '__utmt': '1',
    'mbox': 'session#1728126804287-257571#1728130054|check#true#1728128254',
    '__utmb': '125690133.8.9.1728128193952',
    'ckcy': '2',
    'cklg': 'ja',
}

headers = {
    'accept': '*/*',
    'accept-language': 'en-GB,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,en-SG;q=0.6,en-US;q=0.5',
    # 'cookie': 'rieSh3Ee_ga=GA1.1.928391635.1711867150; _yjsu_yjad=1711867150.e0d8b076-7218-4c71-a9c6-ee3021ac7de2; _dga=GA1.3.1802963100.1711867142; _ga=GA1.3.1802963100.1711867142; i3_ab=7f000851-439f-49f0-8619-f631fcb679be; _tt_enable_cookie=1; _ttp=Yd1R05Iq1z2XEF4UdIMdBmviasZ; digital[play_volume]=0.5; adpf_uid=UQWyxQwICRcVLVpb; uid=dRXBoGDBeOBSEJqtTOdP; suid=dRXBoGDBeOBSEJqtTOdP; check_done_login=true; dtms=10; d_mylibrary=nINks%2BxgI%2F1I329WV6UBoA%3D%3D; universe_aid=350ce30483a87c8e22f7a652a0055267; d_certify=2024-03-31+15%3A44%3A33; digital[play_muted]=1; deviceIdentify=TqiLBvL2steK6atdgAwBkMWwe2mtjb; top_dummy=355138b2-e0d1-41a3-a572-abef455215e6; digital[play_heatmap]=1; subscription_members_status=non; guest_id=VxZRShRMC0pCVQcP; dtmu=YToyOntzOjI6Iml2IjtzOjg6IiqckZos_j4ZIjtzOjU6InZhbHVlIjtzOjI0OiISSVwxDtQ2LTylnBLQCuERSiqfGXQpouEiO30; dtmh=3.b10b67e794d0ac573f6e792aacc6c130058bd055338a4951e6ffb265a331b90f; _cq_duid=1.1723207646.J6hWbU0LNYD2PoP4; _clck=68vg3q%7C2%7Cfoe%7C0%7C1690; top_pv_uid=8bfb0ca0-11a9-4cf9-bca2-2e2be689d79e; cdp_id=VkCih9XdqvZITYB6; digital[play_bitrate]=%E9%AB%98%E7%94%BB%E8%B3%AA%20(576p); ixd_lastclick=6828,1726885088; _gcl_au=1.1.776536611.1727485373; age_check_done=1; _gid=GA1.3.788114191.1727873719; has_althash=V1ECDEsGUB8IVhEJAwxXDltWBA__; althash=101000-1af2752a-f842-f11d-8df0-0731820d6065; i3_opnd=VkCih9XdqvZITYB6; ckcy_remedied_check=ktkrt_argt; adult_link_disable=1; __utmc=125690133; __utmz=125690133.1728091176.327.213.utmcsr=accounts.dmm.co.jp|utmccn=(referral)|utmcmd=referral|utmcct=/service/login/password/=/path=https%3A%2F%2Fwww.dmm.co.jp%2Fdigital%2F-%2Fmylibrary%2Fsearch%2F; _cq_suid=1.1728091177.HtNYGlvdshEO4J84; licenseUID=be2a1eAa5ed3bA1D18A8dee0A9a991; sort_search=eyJzZWFyY2hzdHIiOiIifQ%3D%3D; list_condition=%7B%22digital%22%3A%7B%22limit%22%3Anull%2C%22sort%22%3A%22date%22%2C%22view%22%3Anull%7D%7D; LSS_SESID=A1lRXE9CCQJYQTR6d0cKEF9WAFkQOxNzQQRVCSQlcycjKCoQVwBfcCMiIHJQRwoQX1EOQWE1JWJtFl1YX1UFUFpTW14DBgIKEVlYCREpYjA6N3EweyVGC1gOVQseFwhbWEEOB0dFbEINERURCBYLV19GUAJGBEYLSg5RC0cAWwULFwMKFgpAC1ZZQ1dSEVRBXhcOVwhDEllcQ0QKFl4CWEBBWRtJ; dig_history=ddh280%2Cntk033%2Cion209%2Csgk145%2Csmjz051%2Chmdnc738%2Cdocs004; is_intarnal=false; INT_SESID=A1lRXE9CCQJYQTR6d0cKEF9XAlkQB1EICQIDUwdJAgZUBk9SUABRHANXVAYeBwRbVlIEVFcHVARfFl1CX1EIQDE3IzRgEwhYWFJWAQtVCFJUUwVYQVtdCht9KGU6N3cxKydAXVULBAsZEFsACUdkKiFGDxAIUlIKGwBWAFdcBgNUTldRVQQeBVsHVh4KVghQSFENV1RSBgdYBAMDBEYJEVhaWERZVF5TBxE%2BWldHChBfVQZZECVVAAlBHwkHBgIRW0FZFQ4ECRMGAT5aV0cKEF9VDkEGQ19DAwNcExAXVxA9CgZED0IJAFRZQ2VYJlgLXDxQEkQ7LWRgdlATXhcIW1hBAxNAWWxFCw4EEQgMC1JSVgxSA1dQBQAPFQtUVQhABhYSCl1SUkULDA8RCBYLU19GFlhBW1UIAxYPQjoFVAQLDwsHQFRsXhUNBEERXlNZVV9JHg%3D%3D; INT_SESID_SECURE=A1lRXE9CCQJYQTR6d0cKEF9XAlkQB1EICQIDUwdJAgZUBk9SUABRHANXVAYeBwRbVlIEVFcHVARfFl1CX1EIQDE3IzRgEwhYWFJWAQtVCFJUUwVYQVtdCht9KGU6N3cxKydAXVULBAsZEFsACUdkKiFGDxAIUlIKGwBWAFdcBgNUTldRVQQeBVsHVh4KVghQSFENV1RSBgdYBAMDBEYJEVhaWERZVF5TBxE%2BWldHChBfVQZZECVVAAlBHwkHBgIRW0FZFQ4ECRMGAT5aV0cKEF9VDkEGQ19DAwNcExAXVxA9CgZED0IJAFRZQ2VYJlgLXDxQEkQ7LWRgdlATXhcIW1hBAxNAWWxFCw4EEQgMC1JSVgxSA1dQBQAPFQtUVQhABhYSCl1SUkULDA8RCBYLU19GFlhBW1UIAxYPQjoFVAQLDwsHQFRsXhUNBEERXlNZVV9JHg%3D%3D; secid=a3faf9e87c749459be32d42be968770f; login_secure_id=a3faf9e87c749459be32d42be968770f; login_session_id=401284a6-57a5-49d7-9393-594f3b7a0e2a; cto_bundle=0TF75l8lMkJzdjFWYmU1QkUzUGRuNGpxJTJGa3ZaOFo1blBnZW9IdjNLcU1FdmtVemQ2dDZZdWN6cDFZS0cyeDc4YndQelElMkJKanVVYmlJVkVtMWdLMEVOSVRjUndIaDlJYURlcURMd0laYVQ4VDJmWmFRamNwdVdEbzFHZENtNGtEMk1iQnRISXlpV0l1REZXSWJ2ekRaNUtLQnlxaEw0aUVRMnd6cGpudGJrMGhFZGFUNndSRUEzbjIlMkJEUTZySnJBJTJGOFFjaE5Jb0tGQWYxeEQzdWhHY011NDRZWnNwUSUzRCUzRA; rieSh3Ee_ga_KQYE0DE5JW=GS1.1.1728114602.67.1.1728116470.0.0.1712278297; __utma=125690133.1802963100.1711867142.1728121435.1728126804.332; __utmt=1; mbox=session#1728126804287-257571#1728130054|check#true#1728128254; __utmb=125690133.8.9.1728128193952; ckcy=2; cklg=ja',
    'origin': 'https://www.dmm.co.jp',
    'priority': 'u=1, i',
    'referer': 'https://www.dmm.co.jp/',
    'sec-ch-ua': '"Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-site',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36',
    'content-type': 'application/x-www-form-urlencoded',
}

data = '{"kids":["2UUiunASM5OGTVhtkmbgMQ","AAAAAAAAAAAAAAAAAAAAAA","eyJ2IjoiMiIsImZpZCI6Ig","MXN0Y3YwMDQwOCIsInN2aQ","ZCI6ImRpZ2l0YWwiLCJwbA","IjoiZXlKd2FXUWlPaUl4Yw","M1JqZGpBd05EQTRJaXdpWg","R1ZzYVhabGNubGZkSGx3Wg","U0k2SW5OMEluMCIsImNzIg","OiIyOWQyYzUzY2NhZGFjMg","MmNmNzZkMmQ2OWMxN2JkZg","YmEifQAAAAAAAAAAAAAAAA"],"type":"temporary","spki":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuwr_yndFasVY9eLZv2jZZjCb3LI9bcB7QNyOzl31P4klOElLp5vg1k3uPOhD7wJau7yDMA4-HUuIFNZ6B2BZOVVr4vEh3EZZXlRnL3mhtaNHd8UKJEyWm5fQDNlKoGW563SFfDZoWXY2gex_RgGxazuF3sepUPp_73sISZGryQV5-46_yMB5L--zE43j5ag3sdr1ao4U_bVG-Ny5gnESismcEE478t6NrS6wRbJKtjzxBrN1r9V7hVYZg9jZ3ope3XynDY-Uls5BtC4EePd92mqZv5MR9wbra8gSjdparu_6bjXPPHDcmXAE_dpLkf7oIq-JJIZWFxzfot-1j6lOKQIDAQAB"}'

response = requests.post('https://mlic.dmm.co.jp/drm/clearkey/license', cookies=cookies, headers=headers, data=data)

**Comment by DevLARLEY** [comment]
Don't know what you did, but this works:
```python
import requests
import base64
from Cryptodome.PublicKey import RSA
from Cryptodome.Cipher import PKCS1_OAEP
from Cryptodome.Hash import SHA256


class ClearKey_RSA:
    def __init__(
            self,
            key_length=2048
    ):
        """
        Decrypts RSA encrypted ClearKey responses
        Author: github.com/DevLARLEY
        """
        self.private_key = RSA.generate(key_length)
        self.public_key = self.private_key.publickey()

    def export_spki(self) -> str:
        spki = self.public_key.export_key(format='DER')
        return base64.b64encode(spki).decode('utf-8')

    @staticmethod
    def pad_b64_to_bytes(encoded_str):
        return base64.b64decode(encoded_str.replace('-', '+').replace('_', '/') + '==')

    def decrypt_key(self, b64_key: str) -> bytes:
        cipher = PKCS1_OAEP.new(self.private_key, hashAlgo=SHA256)
        return cipher.decrypt(self.pad_b64_to_bytes(b64_key))


if __name__ == '__main__':
    rsa = ClearKey_RSA()

    response = requests.post(
        url='https://mlic.dmm.co.jp/drm/clearkey/license',
        cookies={
            'licenseUID': 'be2a1eAa5ed3bA1D18A8dee0A9a991'
        },
        headers={
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36',
        },
        json={
            "kids": [
                "2UUiunASM5OGTVhtkmbgMQ",
                "AAAAAAAAAAAAAAAAAAAAAA",
                "eyJ2IjoiMiIsImZpZCI6Ig",
                "MXN0Y3YwMDQwOCIsInN2aQ",
                "ZCI6ImRpZ2l0YWwiLCJwbA",
                "IjoiZXlKd2FXUWlPaUl4Yw",
                "M1JqZGpBd05EQTRJaXdpWg",
                "R1ZzYVhabGNubGZkSGx3Wg",
                "U0k2SW5OMEluMCIsImNzIg",
                "OiIyOWQyYzUzY2NhZGFjMg",
                "MmNmNzZkMmQ2OWMxN2JkZg",
                "YmEifQAAAAAAAAAAAAAAAA"
            ],
            "spki": rsa.export_spki(),
            "type": "temporary"
        }
    )

    data = response.json()

    for key_data in data['keys']:
        kid_hex = rsa.pad_b64_to_bytes(key_data['kid']).hex()
        decrypted_hex = rsa.decrypt_key(key_data['k']).hex()

        print(f"{kid_hex}:{decrypted_hex}")
```

**Comment by bryanyeong97** [comment]
wow, so amazing, i think i know where got wrong already, i haven set header, thanks admin for help
